### ISSUE TITLE
xfd shows BadLength with emojione-android.ttf and emojione-apple.ttf

### ISSUE THREAD

**Issue by fujiwarat** [Ranks/emojione#295]
Originally reported in https://bugzilla.redhat.com/show_bug.cgi?id=1350700#c2

```
$ fc-list  "Emoji One"
/home/mfabian/.fonts/emojione-android.ttf: Emoji One:style=Regular

$ xfd -fa "Emoji One"
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  138 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  192
  Current serial number in output stream:  657
$ xfd -fa "Apple Color Emoji"
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  138 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  326
  Current serial number in output stream:  514
```

Also ftview shows "Invalid pixel size":
```
ftview 20 /usr/lib/node_modules/emojione/assets/fonts/emojione-android.ttf 
```

**Comment by caseyahenson** [comment]
@fujiwarat I'm sorry for the delayed response, any progress on this issue? We rely on outside contributors for the fonts that we provide, but I'm also seeing this font: https://github.com/eosrei/emojione-color-font in the thread you posted, which is a font built using EmojiOne assets so I want to be sure we're locating the correct source of any issues.

**Comment by miguelsousa** [comment]
@fujiwarat please elaborate on the meaning of **Invalid pixel size**.

**Comment by fujiwarat** [comment]
@miguelsousa You can find that string when you run "ftview" above or see the attachment in https://bugzilla.redhat.com/show_bug.cgi?id=1350700#c3 .

@caseyahenson 
I have no idea which part is the root cause in the source code and I don't have the build environment in either Android or Mac. CC'ing @mike-fabian, @hadess

I got https://github.com/eosrei/emojione-color-font/releases/download/v1.2/EmojiOneColor-SVGinOT-Linux-1.2.tar.gz and the font works fine with xfd and ftview.

**Comment by miguelsousa** [comment]
@fujiwarat I understand where that message is displayed, but that doesn't explain what it's supposed to mean.
Let me put it another way: which part of the font is at fault?

**Comment by fujiwarat** [comment]
@miguelsousa I'm not sure which part is wrong. ftview shows the glyphs in emojione-apple.ttf correctly agaist emojione-android.ttf. Maybe need to debug emojione-android.ttf with the limited number of the glyphs.

When I see the source code ftview, FT_Match_Size() reports "Invalid_Pixel_Size" .
http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/src/base/ftobjs.c#n2640

```
#0  FT_Match_Size (face=0x555555799310, req=0x7fffffffdb40, 
    ignore_width=0 '\000', size_index=0x7fffffffdaa8)
    at /root/rpmbuild/BUILD/freetype-2.6.3/src/base/ftobjs.c:2625
#1  0x00007ffff7b622c0 in tt_face_set_sbit_strike (face=0x555555799310, 
    req=0x7fffffffdb40, astrike_index=0x7fffffffdaa8)
    at /root/rpmbuild/BUILD/freetype-2.6.3/src/sfnt/ttsbit.c:233
#2  0x00007ffff7b0c567 in tt_size_request (size=0x55555579ac50, 
    req=0x7fffffffdb40)
    at /root/rpmbuild/BUILD/freetype-2.6.3/src/truetype/ttdriver.c:299
#3  0x00007ffff7afaa94 in FT_Request_Size (face=0x555555799310, 
    req=0x7fffffffdb40)
    at /root/rpmbuild/BUILD/freetype-2.6.3/src/base/ftobjs.c:2934
#4  0x00007ffff7afabf5 in FT_Set_Char_Size (face=0x555555799310, 
    char_width=1280, char_height=1280, horz_resolution=72, vert_resolution=72)
    at /root/rpmbuild/BUILD/freetype-2.6.3/src/base/ftobjs.c:3021
#5  0x00007ffff7b83acb in ftc_scaler_lookup_size (manager=0x55555577eab0, 
    scaler=0x555555777058, asize=0x555555799250)
    at /root/rpmbuild/BUILD/freetype-2.6.3/src/cache/ftcmanag.c:61
#6  0x00007ffff7b83c8c in ftc_size_node_init (ftcnode=0x555555799240, 
    ftcscaler=0x555555777058, ftcmanager=0x55555577eab0)
    at /root/rpmbuild/BUILD/freetype-2.6.3/src/cache/ftcmanag.c:133
#7  0x00007ffff7b837fb in FTC_MruList_New (list=0x55555577ebb0, 
    key=0x555555777058, anode=0x7fffffffdca0)
    at /root/rpmbuild/BUILD/freetype-2.6.3/src/cache/ftcmru.c:269
#8  0x00007ffff7b83e46 in FTC_Manager_LookupSize (manager=0x55555577eab0, 
    scaler=0x555555777058, asize=0x7fffffffdcf0)
    at /root/rpmbuild/BUILD/freetype-2.6.3/src/cache/ftcmanag.c:200
#9  0x000055555555d120 in FTDemo_Get_Size (handle=0x555555777010, 
    asize=0x7fffffffdd40) at src/ftcommon.c:674
#10 0x0000555555557724 in Render_All (num_indices=1836, offset=0)
    at src/ftview.c:472
#11 0x000055555555ae56 in main (argc=0, argv=0x7fffffffde90)
    at src/ftview.c:1975

2606	    for ( i = 0; i < face->num_fixed_sizes; i++ )
(gdb) 
2625	    return FT_THROW( Invalid_Pixel_Size );
(gdb) print face->num_fixed_sizes
$12 = 1
(gdb) print h
$10 = 1280
(gdb) print bsize->y_ppem
$11 = 6784
```

The height and y_ppem is not equal and causes Invalid_Pixel_Size.

**Comment by dasJ** [comment]
Bumping this up. On the st terminal emulator, this happens as well when trying to paste all emoji characters from getemoji.com
Backtrace:
```
#0  0x00007ffff75c45d0 in _XError () from /usr/lib/libX11.so.6
#1  0x00007ffff75c1617 in ?? () from /usr/lib/libX11.so.6
#2  0x00007ffff75c16d5 in ?? () from /usr/lib/libX11.so.6
#3  0x00007ffff75c1fd5 in _XEventsQueued () from /usr/lib/libX11.so.6
#4  0x00007ffff75a437a in XFlush () from /usr/lib/libX11.so.6
#5  0x000055555556120d in run () at x.c:1678
#6  0x0000555555561533 in main (argc=1, argv=0x7fffffffe310) at x.c:1767
```

**Comment by acannibalox** [comment]
Was this ever resolved? I'm still getting the same issue - also in st.
